name: Livekeys build matrix

on: [push, pull_request]

env:
  CMAKE_VERSION: 3.18.3
  NINJA_VERSION: 1.10.1
  BUILD_TYPE: Release
  CCACHE_VERSION: 3.7.7

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "macOS Latest Clang", artifact: "macOS.7z",
            os: macos-latest,
            cc: "clang", cxx: "clang++"
          }

    steps:
    - uses: actions/checkout@v1

    - name: Download dependencies
      run:|
        brew tap livekeys-opencv
        then brew update
        HOMEBREW_NO_AUTO_UPDATE=1 brew install openssl
        HOMEBREW_NO_AUTO_UPDATE=1 brew install wget
        wget --help