name: Livekeys build matrix

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        include:
        - os: macos-latest
          NAME: macos
          TARGET: x86_64-apple-darwin
          COMPILER: clang
          LINKER: clang

    steps:
      - uses: actions/checkout@v1
      - name: Download dependencies
        run: |
          brew tap livekeys-opencv
          then brew update
          HOMEBREW_NO_AUTO_UPDATE=1 brew install openssl
          HOMEBREW_NO_AUTO_UPDATE=1 brew install wget
          wget --help
        
        
